import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://specnota-nextgen.herokuapp.com/');
  await page.getByPlaceholder('abrahamjohn@gmail.com').click();
  await page.getByPlaceholder('abrahamjohn@gmail.com').fill('okolijohnson69@gmail.com');
  await page.getByPlaceholder('******').click();
  await page.getByPlaceholder('******').fill('12345678');
  await page.getByRole('button', { name: 'Log In' }).click();
  await page.pause()
  await page.locator('.toggler').click();
  await page.getByText('Notification').click();
  await page.locator('label').filter({ hasText: 'Click to receive notification for projects.' }).locator('svg').click();
  await page.locator('label').filter({ hasText: 'Click to receive notification for projects.' }).locator('span').first().click();
  await page.locator('label').filter({ hasText: 'Click to receive notification for documents.' }).locator('svg').click();
  await page.locator('label').filter({ hasText: 'Click to receive notification for annotations.' }).locator('svg').click();
  await page.locator('label').filter({ hasText: 'Click to receive notification for projects.' }).locator('svg').click();
  await page.locator('label').filter({ hasText: 'Click to receive notification for review task actions.' }).locator('span').first().click();
  await page.locator('label').filter({ hasText: 'Click to receive notification for updated task actions.' }).locator('span').first().click();
  await page.locator('label').filter({ hasText: 'Click to receive notification for created task actions.' }).locator('svg').click();
  await page.locator('label').filter({ hasText: 'Click to receive notification for assigned task actions.' }).locator('div').click();
  await page.locator('label').filter({ hasText: 'Click to receive notification for task comments.' }).locator('svg').click();
  await page.locator('label').filter({ hasText: 'Click to receive notification for tasks.' }).locator('div').click();
  await page.locator('label').filter({ hasText: 'Click to receive notification for promotions.' }).locator('div').click();
  await page.locator('label').filter({ hasText: 'Click to receive notification for services.' }).locator('span').first().click();
  await page.locator('label').filter({ hasText: 'Click to receive notification for promotions.' }).locator('span').first().click();
  await page.locator('label').filter({ hasText: 'Click to receive notification for tasks.' }).locator('span').first().click();
  await page.locator('label').filter({ hasText: 'Click to receive notification for task comments.' }).locator('span').first().click();
  await page.locator('label').filter({ hasText: 'Click to receive notification for assigned task actions.' }).locator('span').first().click();
  await page.locator('label').filter({ hasText: 'Click to receive notification for created task actions.' }).locator('span').first().click();
  await page.locator('label').filter({ hasText: 'Click to receive notification for updated task actions.' }).locator('span').first().click();
  await page.locator('label').filter({ hasText: 'Click to receive notification for review task actions.' }).locator('span').first().click();
  await page.locator('label').filter({ hasText: 'Click to receive notification for projects.' }).locator('span').first().click();
  await page.locator('label').filter({ hasText: 'Click to receive notification for documents.' }).locator('span').first().click();
  await page.locator('label').filter({ hasText: 'Click to receive notification for annotations.' }).locator('span').first().click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('link', { name: 'Teams' }).click();
  await page.getByRole('link', { name: 'Subscription' }).click();
  await page.locator('span').nth(2).click();
  await page.locator('span').nth(1).click();
  await page.getByRole('link', { name: 'Account' }).click();
  await page.locator('input[name="oldPassword"]').click();
  await page.locator('input[name="newPassword"]').click();
  await page.getByRole('button', { name: 'Change' }).click();
  await page.getByRole('link', { name: 'Profile' }).click();
  await page.locator('input[name="firstName"]').click();
  await page.locator('input[name="lastName"]').click();
  await page.locator('textarea[name="description"]').click();
  await page.getByRole('button', { name: 'Save' }).click();
  await page.locator('svg').first().click();
  await page.locator('svg').first().click();
  await page.locator('path').first().click();
  await page.locator('svg').first().click();
  await page.locator('svg').first().click();
});